apiVersion: v1
kind: Pod
metadata:
  name: rabbit-consumer-pod
spec:
  containers:
    - name: rabbit-consumer-container
      image: rabbitconsumer:latest  # Docker imajınızın adı ve etiketi
      command: ["java", "-jar", "rabbitConsumer-1.0-SNAPSHOT.jar"]  # Uygulamanın başlatılacağı komut